# Generated by Django 2.0.6 on 2018-06-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norlonn', '0002_auto_20150602_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norlonnreport',
            options={'permissions': (('generate_report', 'Can generate norlønn report'), ('export_report', 'Can view norlønn reports'))},
        ),
    ]
