# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to consolidate the apps of events, invoices and workers into one.
    Note how it replaces all the migrations for the other applications, as we truly
    merge them all into this one and single app.
    """

    initial = True

    dependencies = [
        ('norlonn', '0002_auto_20150602_1738'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=10)),
                ('invoice_email', models.EmailField(default='', max_length=254)),
                ('default_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(unique=True)),
                ('period', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                              to='society.Society')),
            ],
            options={
                'permissions': (
                    ('close_period', 'Can close periods to generate invoices'),
                    ('mark_paid', 'Can mark invoices as paid')),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active',
                 models.BooleanField(default=True, help_text='Check off if the worker is still actively working.',
                                     verbose_name='active')),
                ('name',
                 models.CharField(help_text='Full name, with first name first.', max_length=1000, verbose_name='name')),
                ('address', models.CharField(help_text='Full address including postal code and area.', max_length=1000,
                                             verbose_name='address')),
                ('account_no',
                 models.CharField(blank=True, help_text='Norwegian bank account number, no periods, 11 digits.',
                                  max_length=20, verbose_name='account no.')),
                ('person_id', models.CharField(blank=True, max_length=20)),
                ('norlonn_number', models.IntegerField(blank=True,
                                                       help_text='Employee number in the wage system, Norl&oslash;nn. <strong>Must</strong> exist and be correct!',
                                                       null=True, unique=True, verbose_name='norl&oslash;nn number')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers',
                                              to='society.Society')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date', models.DateField(verbose_name='event date')),
                ('registered', models.DateField(auto_now_add=True, verbose_name='registered')),
                ('processed', models.DateField(blank=True, null=True, verbose_name='processed')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                              related_name='in_invoice', to='society.Invoice',
                                              verbose_name='invoice')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='society',
                                              to='society.Society')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='wage')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='hours')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.Event')),
                ('norlonn_report',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='in_report', to='norlonn.NorlonnReport',
                                   verbose_name='norl&oslash;nn report')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker',
                                             to='society.Worker', verbose_name='worker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set([('event', 'worker')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='events', to='society.Invoice', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts',
                                    to='society.Event'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='norlonn_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='shifts', to='norlonn.NorlonnReport',
                                    verbose_name='norl&oslash;nn report'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts',
                                    to='society.Worker', verbose_name='worker'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('period', 'society')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='events', to='society.Invoice', verbose_name='invoice'),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (
                ('close_period', 'Can close periods to generate invoices'), ('mark_paid', 'Can mark invoices as paid')),
                'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'shift', 'verbose_name_plural': 'shifts'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'society', 'verbose_name_plural': 'societies'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AlterField(
            model_name='society',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='events', to='society.Invoice', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='event',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='society',
                                    to='society.Society', verbose_name='society'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='invoice paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period',
            field=models.DateField(verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices',
                                    to='society.Society', verbose_name='society'),
        ),
        migrations.AlterField(
            model_name='society',
            name='default_wage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='default wage per hour'),
        ),
        migrations.AlterField(
            model_name='society',
            name='invoice_email',
            field=models.EmailField(default='', max_length=254, verbose_name='invoice e-mail'),
        ),
        migrations.AlterField(
            model_name='society',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='society',
            name='shortname',
            field=models.CharField(max_length=10, verbose_name='abbreviated name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='person_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='person ID'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers',
                                    to='society.Society', verbose_name='society'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(default=None, help_text='User which closed the period the invoice belongs to.',
                                    null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
