# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_invoices_change_fkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'permissions': (('close_period', 'Can close periods to generate invoices'), ('mark_paid', 'Can mark invoices as paid')), 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'shift', 'verbose_name_plural': 'shifts'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'society', 'verbose_name_plural': 'societies'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AlterField(
            model_name='society',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
