# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('society', '0009_meta_and_logo_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='events', to='society.Invoice', verbose_name='invoice'),
        ),
        migrations.AlterField(
            model_name='event',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='society',
                                    to='society.Society', verbose_name='society'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='invoice paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period',
            field=models.DateField(verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices',
                                    to='society.Society', verbose_name='society'),
        ),
        migrations.AlterField(
            model_name='society',
            name='default_wage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='default wage per hour'),
        ),
        migrations.AlterField(
            model_name='society',
            name='invoice_email',
            field=models.EmailField(default='', max_length=254, verbose_name='invoice e-mail'),
        ),
        migrations.AlterField(
            model_name='society',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='society',
            name='shortname',
            field=models.CharField(max_length=10, verbose_name='abbreviated name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='person_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='person ID'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers',
                                    to='society.Society', verbose_name='society'),
        ),
    ]
