---
version: '3.7'

# This is NOT a development version which enables the application to run
# using the production-ready image, while still using local application
# files to enable development.

services:
  spbm:
    build: .
    expose:
      - 8435
    #restart: always
    volumes:
      # Share static files with nginx proxy
      - static-volume:/usr/src/app/static_files
    environment:
      - VIRTUAL_PROTO=uwsgi
      - VIRTUAL_HOST=app.spf.no
      - VIRTUAL_PORT=8435
      - LETSENCRYPT_TEST=true
      - LETSENCRYPT_HOST=app.spf.no
      - LETSENCRYPT_EMAIL=spf-styret@studorg.uio.no

  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./container/nginx.vhost.default:/etc/nginx/vhost.d/default
      - cert-volume:/etc/nginx/certs:ro
      - vhost-volume:/etc/nginx/vhost.d
      - static-volume:/usr/src/static
      - html-volume:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'

        #  nginx-companion:
        #    container_name: nginx-letsencrypt
        #    depends_on:
        #      - nginx-proxy
        #    restart: always
        #    image: jrcs/letsencrypt-nginx-proxy-companion
        #    volumes:
        #      - /var/run/docker.sock:/var/run/docker.sock:ro
        #      - cert-volume:/etc/nginx/certs:rw
        #      - vhost-volume:/etc/nginx/vhost.d
        #      - html-volume:/usr/share/nginx/html

volumes:
  # Used to share static files with nginx directly
  static-volume:
  # Used to synchcronise Let's Encrypt certificates
  cert-volume:
  # Used to synchcronise Let's Encrypt vhost configurations
  vhost-volume:
  # Used to perform Let's Encrypt certificate requests and confirmation
  html-volume:
