---
version: '3.7'

# This is the BASE docker-compose file, specifying the baseline settings for
# SPBM. When executing "docker-compose up" this file and the override file
# docker-compose.override.yml will be loaded which overrides certain parts.
#
# For a production environment you must manually specify the production
# compose file and the base with:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml <args>

services:
  spbm:
    container_name: app
    image: spbm
    build: .
    expose:
      - 8000
    volumes:
      # Share static files with nginx proxy
      - static-volume:/usr/src/app/static_files
    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8000
    env_file:
      - ./container/spbm.env
  postgres:
    container_name: psql
    # Note that psycopg2 is the main requirement for PSQL support, not Django
    # itself per se. Thus, to upgrade PostgreSQL check psycopg2 support.
    image: postgres:10.11
    ports:
      - 5432:5432
    # "Sane" defaults that are overwritten
    env_file:
      - ./container/postgres.env
  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./container/nginx.vhost.default:/etc/nginx/vhost.d/default
      - cert-volume:/etc/nginx/certs:ro
      - vhost-volume:/etc/nginx/vhost.d
      - static-volume:/usr/src/static
      - html-volume:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true

        #  nginx-companion:
        #    container_name: nginx-letsencrypt
        #    depends_on:
        #      - nginx-proxy
        #    restart: always
        #    image: jrcs/letsencrypt-nginx-proxy-companion
        #    volumes:
        #      - /var/run/docker.sock:/var/run/docker.sock:ro
        #      - cert-volume:/etc/nginx/certs:rw
        #      - vhost-volume:/etc/nginx/vhost.d
        #      - html-volume:/usr/share/nginx/html

volumes:
  # Used to share static files with nginx directly
  static-volume:
  # Used to synchcronise Let's Encrypt certificates
  cert-volume:
  # Used to synchcronise Let's Encrypt vhost configurations
  vhost-volume:
  # Used to perform Let's Encrypt certificate requests and confirmation
  html-volume:
