# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_change_fkey'),
    ]

    database_operations = [
        migrations.AlterModelTable('Shift', 'society_shift'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations)
    ]

