# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spfuser',
            options={'verbose_name': 'SPF-user', 'verbose_name_plural': 'SPF-users'},
        ),
        migrations.AlterField(
            model_name='spfuser',
            name='society',
            field=models.ForeignKey(help_text='The society within SPF that the user has as a primary connection.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='society.Society', verbose_name='Society'),
        ),
    ]
